# Generated by Django 4.0.1 on 2022-05-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.IntegerField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'Collection_t',
            },
        ),
        migrations.CreateModel(
            name='CommunicateContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.IntegerField()),
                ('member', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'communcation_t',
            },
        ),
        migrations.CreateModel(
            name='Favorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('nft_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Favorite_t',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128)),
                ('name', models.TextField(null=True)),
                ('interduction', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('PFP', models.TextField(null=True)),
                ('InjoinDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'member_t',
            },
        ),
        migrations.CreateModel(
            name='NFTProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('ipfs', models.TextField()),
                ('creator', models.CharField(blank=True, max_length=128)),
                ('topic', models.CharField(blank=True, max_length=10)),
                ('num', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(null=True)),
                ('royalties', models.IntegerField(default='10')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'nft_t',
            },
        ),
        migrations.CreateModel(
            name='Resell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('nft_id', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Resell_t',
            },
        ),
        migrations.CreateModel(
            name='Royaltie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('nft_id', models.IntegerField()),
                ('royalties', models.IntegerField()),
            ],
            options={
                'db_table': 'royalties_t',
            },
        ),
        migrations.CreateModel(
            name='SocialHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releasehash', models.TextField()),
                ('title', models.TextField()),
                ('classification', models.CharField(choices=[('PFP', 'PFP'), ('ArtWork', 'ArtWork'), ('Music', 'Music'), ('Game', 'Game')], default='PFP', max_length=9)),
                ('content', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('route', models.TextField(null=True)),
                ('nft_id', models.IntegerField(null=True)),
                ('date', models.TextField(null=True)),
            ],
            options={
                'db_table': 'SocialHall_t',
            },
        ),
        migrations.CreateModel(
            name='SocialHallResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('content', models.TextField(null=True)),
                ('titleID', models.IntegerField()),
                ('date', models.TextField(null=True)),
            ],
            options={
                'db_table': 'SocialHallResponse_t',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('price', models.FloatField()),
                ('fromaddress', models.TextField()),
                ('toaddress', models.TextField()),
                ('nft_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_t',
            },
        ),
    ]
