# Generated by Django 4.0.1 on 2022-03-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftproduct',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
