# Generated by Django 4.0.1 on 2022-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nftproduct_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('nft_id', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Resell_t',
            },
        ),
    ]
